package com.applovin.impl.sdk.b;

import com.applovin.mediation.adapters.AppLovinMediationAdapter;
import java.util.concurrent.TimeUnit;

public class c extends d {
   public static final d A;
   public static final d B;
   public static final d C;
   public static final d D;
   public static final d E;
   public static final d F;
   public static final d G;
   public static final d H;
   public static final d I;
   public static final d J;
   public static final d K;
   public static final d L;
   public static final d M;
   public static final d N;
   public static final d O;
   public static final d P;
   public static final d Q;
   public static final d R;
   public static final d S;
   public static final d T;
   public static final d a = a("afi", "");
   public static final d b;
   public static final d c;
   public static final d d;
   public static final d e;
   public static final d f;
   public static final d g;
   public static final d h;
   public static final d i;
   public static final d j;
   public static final d k;
   public static final d l;
   public static final d m;
   public static final d n;
   public static final d o;
   public static final d p;
   public static final d q;
   public static final d r;
   public static final d s;
   public static final d t;
   public static final d u;
   public static final d v;
   public static final d w;
   public static final d x;
   public static final d y;
   public static final d z;

   static {
      b = a("afi_ms", TimeUnit.SECONDS.toMillis(5L));
      c = a("mediation_endpoint", "https://ms.applovin.com/");
      d = a("mediation_backup_endpoint", "https://ms.applvn.com/");
      e = a("fetch_next_ad_retry_delay_ms", TimeUnit.SECONDS.toMillis(2L));
      f = a("fetch_next_ad_timeout_ms", TimeUnit.SECONDS.toMillis(5L));
      g = a("fetch_mediation_debugger_info_timeout_ms", TimeUnit.SECONDS.toMillis(7L));
      Boolean var0 = true;
      h = a("pass_extra_parameters", var0);
      i = a("postback_macros", "{\"{MCODE}\":\"mcode\",\"{BCODE}\":\"bcode\",\"{ICODE}\":\"icode\",\"{SCODE}\":\"scode\"}");
      Boolean var1 = false;
      j = a("persistent_mediated_postbacks", var1);
      k = a("max_signal_provider_latency_ms", TimeUnit.SECONDS.toMillis(30L));
      Integer var2 = 20;
      l = a("max_adapter_version_length", var2);
      m = a("max_adapter_sdk_version_length", var2);
      n = a("max_adapter_signal_length", 5120);
      o = a("default_adapter_timeout_ms", TimeUnit.SECONDS.toMillis(10L));
      Integer var3 = -2;
      p = a("default_ad_view_width", var3);
      q = a("default_ad_view_height", var3);
      r = a("ad_refresh_ms", TimeUnit.SECONDS.toMillis(30L));
      s = a("ad_load_failure_refresh_ms", TimeUnit.SECONDS.toMillis(30L));
      t = a("ad_load_failure_refresh_ignore_error_codes", "204");
      u = a("refresh_ad_on_app_resume_elapsed_threshold_ms", 0L);
      v = a("refresh_ad_view_timer_responds_to_background", var0);
      w = a("refresh_ad_view_timer_responds_to_store_kit", var0);
      x = a("refresh_ad_view_timer_responds_to_window_visibility_changed", var1);
      Long var4 = 150L;
      y = a("ad_view_fade_in_animation_ms", var4);
      z = a("ad_view_fade_out_animation_ms", var4);
      A = a("fullscreen_display_delay_ms", 600L);
      B = a("ahdm", 500L);
      C = a("ad_view_refresh_precache_request_viewability_undesired_flags", 118L);
      D = a("ad_view_refresh_precache_request_delay_ms", TimeUnit.SECONDS.toMillis(2L));
      E = a("ad_view_block_publisher_load_if_refresh_scheduled", var0);
      F = a("fullscreen_ads_block_publisher_load_if_another_showing", var0);
      G = a("fabsina", var1);
      H = a("ad_expiration_ms", TimeUnit.HOURS.toMillis(4L));
      I = a("saewib", var1);
      J = a("utaoae", var1);
      K = a("ad_hidden_timeout_ms", -1L);
      L = a("schedule_ad_hidden_on_ad_dismiss", var1);
      M = a("ad_hidden_on_ad_dismiss_callback_delay_ms", TimeUnit.SECONDS.toMillis(1L));
      N = a("proe", var1);
      O = a("fitaui", "");
      P = a("finaui", "");
      Q = a("faespcn", AppLovinMediationAdapter.class.getName());
      R = a("fard_s", 3L);
      S = a("mute_state", 2);
      T = a("adapters_to_re_fetch_sdk_version_if_empty", var0);
   }
}
