package com.applovin.impl.sdk.b;

import android.net.Uri;
import com.applovin.impl.a.j;
import com.applovin.impl.adview.AppLovinTouchToClickListener;
import com.applovin.sdk.AppLovinAdSize;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class d implements Comparable {
   public static final d U;
   public static final d V;
   public static final d W;
   public static final d X;
   public static final d Y;
   public static final d Z;
   private static final List a;
   public static final d aA;
   public static final d aB;
   public static final d aC;
   public static final d aD;
   public static final d aE;
   public static final d aF;
   public static final d aG;
   public static final d aH;
   public static final d aI;
   public static final d aJ;
   public static final d aK;
   public static final d aL;
   public static final d aM;
   public static final d aN;
   public static final d aO;
   public static final d aP;
   public static final d aQ;
   public static final d aR;
   public static final d aS;
   public static final d aT;
   public static final d aU;
   public static final d aV;
   public static final d aW;
   public static final d aX;
   public static final d aY;
   public static final d aZ;
   public static final d aa;
   public static final d ab;
   public static final d ac;
   public static final d ad;
   public static final d ae;
   public static final d af;
   public static final d ag;
   public static final d ah;
   public static final d ai;
   public static final d aj;
   public static final d ak;
   public static final d al;
   public static final d am;
   public static final d an;
   public static final d ao;
   public static final d ap;
   public static final d aq;
   public static final d ar;
   public static final d as;
   public static final d at;
   public static final d au;
   public static final d av;
   public static final d aw;
   public static final d ax;
   public static final d ay;
   public static final d az;
   private static final Map b;
   public static final d bA;
   public static final d bB;
   public static final d bC;
   public static final d bD;
   public static final d bE;
   public static final d bF;
   public static final d bG;
   public static final d bH;
   public static final d bI;
   public static final d bJ;
   public static final d bK;
   public static final d bL;
   public static final d bM;
   public static final d bN;
   public static final d bO;
   public static final d bP;
   public static final d bQ;
   public static final d bR;
   public static final d bS;
   public static final d bT;
   public static final d bU;
   public static final d bV;
   public static final d bW;
   public static final d bX;
   public static final d bY;
   public static final d bZ;
   public static final d ba;
   public static final d bb;
   public static final d bc;
   public static final d bd;
   public static final d be;
   public static final d bf;
   public static final d bg;
   public static final d bh;
   public static final d bi;
   public static final d bj;
   public static final d bk;
   public static final d bl;
   public static final d bm;
   public static final d bn;
   public static final d bo;
   public static final d bp;
   public static final d bq;
   public static final d br;
   public static final d bs;
   public static final d bt;
   public static final d bu;
   public static final d bv;
   public static final d bw;
   public static final d bx;
   public static final d by;
   public static final d bz;
   public static final d cA;
   public static final d cB;
   public static final d cC;
   public static final d cD;
   public static final d cE;
   public static final d cF;
   public static final d cG;
   public static final d cH;
   public static final d cI;
   public static final d cJ;
   public static final d cK;
   public static final d cL;
   public static final d cM;
   public static final d cN;
   public static final d cO;
   public static final d cP;
   public static final d cQ;
   public static final d cR;
   public static final d cS;
   public static final d cT;
   public static final d cU;
   public static final d cV;
   public static final d cW;
   public static final d cX;
   public static final d cY;
   public static final d cZ;
   public static final d ca;
   public static final d cb;
   public static final d cc;
   public static final d cd;
   public static final d ce;
   public static final d cf;
   public static final d cg;
   public static final d ch;
   public static final d ci;
   public static final d cj;
   public static final d ck;
   public static final d cl;
   public static final d cm;
   public static final d cn;
   public static final d co;
   public static final d cp;
   public static final d cq;
   public static final d cr;
   public static final d cs;
   public static final d ct;
   public static final d cu;
   public static final d cv;
   public static final d cw;
   public static final d cx;
   public static final d cy;
   public static final d cz;
   public static final d dA;
   public static final d dB;
   public static final d dC;
   public static final d dD;
   public static final d dE;
   public static final d dF;
   public static final d dG;
   public static final d dH;
   public static final d dI;
   public static final d dJ;
   public static final d dK;
   public static final d dL;
   public static final d dM;
   public static final d dN;
   public static final d dO;
   public static final d dP;
   public static final d dQ;
   public static final d dR;
   public static final d dS;
   public static final d dT;
   public static final d dU;
   public static final d dV;
   public static final d dW;
   public static final d dX;
   public static final d dY;
   public static final d dZ;
   public static final d da;
   public static final d db;
   public static final d dc;
   public static final d dd;
   public static final d de;
   public static final d df;
   public static final d dg;
   public static final d dh;
   public static final d di;
   public static final d dj;
   public static final d dk;
   public static final d dl;
   public static final d dm;
   public static final d dn;
   public static final d do;
   public static final d dp;
   public static final d dq;
   public static final d dr;
   public static final d ds;
   public static final d dt;
   public static final d du;
   public static final d dv;
   public static final d dw;
   public static final d dx;
   public static final d dy;
   public static final d dz;
   public static final d eA;
   public static final d eB;
   public static final d eC;
   public static final d eD;
   public static final d eE;
   public static final d eF;
   public static final d eG;
   public static final d eH;
   public static final d eI;
   public static final d eJ;
   public static final d eK;
   public static final d eL;
   public static final d eM;
   public static final d eN;
   public static final d eO;
   public static final d eP;
   public static final d eQ;
   public static final d eR;
   public static final d eS;
   public static final d eT;
   public static final d eU;
   public static final d eV;
   public static final d eW;
   public static final d eX;
   public static final d eY;
   public static final d eZ;
   public static final d ea;
   public static final d eb;
   public static final d ec;
   public static final d ed;
   public static final d ee;
   public static final d ef;
   public static final d eg;
   public static final d eh;
   public static final d ei;
   public static final d ej;
   public static final d ek;
   public static final d el;
   public static final d em;
   public static final d en;
   public static final d eo;
   public static final d ep;
   public static final d eq;
   public static final d er;
   public static final d es;
   public static final d et;
   public static final d eu;
   public static final d ev;
   public static final d ew;
   public static final d ex;
   public static final d ey;
   public static final d ez;
   public static final d fa;
   public static final d fb;
   public static final d fc;
   public static final d fd;
   public static final d fe;
   public static final d ff;
   public static final d fg;
   public static final d fh;
   public static final d fi;
   private final String c;
   private final Object d;

   static {
      Class[] var0 = new Class[5];
      Integer var1 = 0;
      Boolean var2 = false;
      var0[0] = Boolean.class;
      Integer var3 = 1;
      Boolean var4 = true;
      var0[1] = Float.class;
      var0[2] = Integer.class;
      var0[3] = Long.class;
      var0[4] = String.class;
      a = Arrays.asList(var0);
      b = new HashMap(512);
      U = a("empty", var4);
      V = a("dls", "");
      W = a("is_disabled", var2);
      X = a("device_id", "");
      Y = a("device_token", "");
      Z = a("is_verbose_logging", var2);
      aa = a("sc", "");
      ab = a("sc2", "");
      ac = a("server_installed_at", "");
      ad = a("trn", var2);
      ae = a("honor_publisher_settings", var4);
      af = a("track_network_response_codes", var2);
      ag = a("submit_network_response_codes", var2);
      ah = a("clear_network_response_codes_on_request", var4);
      ai = a("clear_completion_callback_on_failure", var2);
      Long var5 = 0L;
      aj = a("sicd_ms", var5);
      ak = a("logcat_max_line_size", 1000);
      al = a("stps", 32);
      am = a("ustp", var2);
      an = a("publisher_can_show_consent_dialog", var4);
      ao = a("consent_dialog_url", "https://assets.applovin.com/gdpr/flow_v1/gdpr-flow-1.html");
      ap = a("consent_dialog_immersive_mode_on", var2);
      aq = a("consent_dialog_show_from_alert_delay_ms", 450L);
      ar = a("alert_consent_for_dialog_rejected", var2);
      as = a("alert_consent_for_dialog_closed", var2);
      at = a("alert_consent_for_dialog_closed_with_back_button", var2);
      au = a("alert_consent_after_init", var2);
      av = a("alert_consent_after_init_interval_ms", TimeUnit.MINUTES.toMillis(5L));
      aw = a("alert_consent_after_dialog_rejection_interval_ms", TimeUnit.MINUTES.toMillis(30L));
      ax = a("alert_consent_after_dialog_close_interval_ms", TimeUnit.MINUTES.toMillis(5L));
      ay = a("alert_consent_after_dialog_close_with_back_button_interval_ms", TimeUnit.MINUTES.toMillis(5L));
      az = a("alert_consent_after_cancel_interval_ms", TimeUnit.MINUTES.toMillis(10L));
      aA = a("alert_consent_reschedule_interval_ms", TimeUnit.MINUTES.toMillis(5L));
      aB = a("text_alert_consent_title", "Make this App Better and Stay Free!");
      aC = a("text_alert_consent_body", "If you don't give us consent to use your data, you will be making our ability to support this app harder, which may negatively affect the user experience.");
      aD = a("text_alert_consent_yes_option", "I Agree");
      aE = a("text_alert_consent_no_option", "Cancel");
      aF = a("ttc_max_click_duration_ms", TimeUnit.SECONDS.toMillis(1L));
      Integer var6 = 10;
      aG = a("ttc_max_click_distance_dp", var6);
      aH = a("ttc_acrs", AppLovinTouchToClickListener.ClickRecognitionState.DISABLED.ordinal());
      aI = a("whitelisted_postback_endpoints", "https://prod-a.applovin.com,https://rt.applovin.com/4.0/pix, https://rt.applvn.com/4.0/pix,https://ms.applovin.com/,https://ms.applvn.com/");
      aJ = a("fetch_settings_endpoint", "https://ms.applovin.com/");
      aK = a("fetch_settings_backup_endpoint", "https://ms.applvn.com/");
      aL = a("adserver_endpoint", "https://a.applovin.com/");
      aM = a("adserver_backup_endpoint", "https://a.applvn.com/");
      aN = a("api_endpoint", "https://d.applovin.com/");
      aO = a("api_backup_endpoint", "https://d.applvn.com/");
      aP = a("event_tracking_endpoint_v2", "https://rt.applovin.com/");
      aQ = a("event_tracking_backup_endpoint_v2", "https://rt.applvn.com/");
      aR = a("fetch_variables_endpoint", "https://ms.applovin.com/");
      aS = a("fetch_variables_backup_endpoint", "https://ms.applvn.com/");
      aT = a("token_type_prefixes_r", "4!");
      aU = a("token_type_prefixes_arj", "json_v3!");
      aV = a("top_level_events", "landing,paused,resumed,checkout,iap");
      aW = a("events_enabled", var4);
      StringBuilder var7 = new StringBuilder();
      var7.append(String.class.getName());
      var7.append(",");
      var7.append(Integer.class.getName());
      var7.append(",");
      var7.append(Long.class.getName());
      var7.append(",");
      var7.append(Double.class.getName());
      var7.append(",");
      var7.append(Float.class.getName());
      var7.append(",");
      var7.append(Date.class.getName());
      var7.append(",");
      var7.append(Uri.class.getName());
      var7.append(",");
      var7.append(List.class.getName());
      var7.append(",");
      var7.append(Map.class.getName());
      aX = a("valid_super_property_types", var7.toString());
      aY = a("persist_super_properties", var4);
      aZ = a("super_property_string_max_length", 1024);
      ba = a("super_property_url_max_length", 1024);
      bb = a("preload_callback_timeout_seconds", -1);
      bc = a("ad_preload_enabled", var4);
      bd = a("ad_auto_preload_sizes", "");
      be = a("ad_auto_preload_incent", var4);
      bf = a("ad_auto_preload_native", var2);
      bg = a("preload_native_ad_on_dequeue", var2);
      bh = a("preload_capacity_banner_regular", var1);
      bi = a("preload_capacity_mrec_regular", var1);
      bj = a("preload_capacity_leader_regular", var1);
      bk = a("preload_capacity_inter_regular", var1);
      bl = a("preload_capacity_inter_videoa", var1);
      bm = a("use_per_format_cache_queues", var4);
      Integer var25 = 15;
      bn = a("extended_preload_capacity_banner_regular", var25);
      bo = a("extended_preload_capacity_mrec_regular", var25);
      bp = a("extended_preload_capacity_leader_regular", var25);
      bq = a("extended_preload_capacity_inter_regular", var25);
      br = a("extended_preload_capacity_inter_videoa", var25);
      bs = a("preload_capacity_zone", var3);
      bt = a("preload_capacity_zone_native", var3);
      bu = a("extended_preload_capacity_zone", var25);
      bv = a("preload_capacity_native_native", var1);
      bw = a("preload_merge_init_tasks_inter_regular", var2);
      bx = a("preload_merge_init_tasks_inter_videoa", var2);
      by = a("preload_merge_init_tasks_banner_regular", var2);
      bz = a("preload_merge_init_tasks_mrec_regular", var2);
      bA = a("preload_merge_init_tasks_leader_regular", var2);
      bB = a("preload_merge_init_tasks_zones", var2);
      bC = a("honor_publisher_settings_verbose_logging", var4);
      bD = a("honor_publisher_settings_auto_preload_ad_sizes", var4);
      bE = a("honor_publisher_settings_auto_preload_ad_types", var4);
      bF = a("cache_cleanup_enabled", var2);
      bG = a("cache_file_ttl_seconds", TimeUnit.DAYS.toSeconds(1L));
      bH = a("cache_max_size_mb", -1);
      bI = a("precache_delimiters", ")]',");
      bJ = a("native_auto_cache_preload_resources", var4);
      bK = a("ad_resource_caching_enabled", var4);
      bL = a("fail_ad_load_on_failed_video_cache", var4);
      bM = a("resource_cache_prefix", "https://vid.applovin.com/,https://pdn.applovin.com/,https://img.applovin.com/,https://d.applovin.com/,https://assets.applovin.com/,https://cdnjs.cloudflare.com/,http://vid.applovin.com/,http://pdn.applovin.com/,http://img.applovin.com/,http://d.applovin.com/,http://assets.applovin.com/,http://cdnjs.cloudflare.com/");
      bN = a("preserved_cached_assets", "sound_off.png,sound_on.png,closeOptOut.png,1381250003_28x28.png,zepto-1.1.3.min.js,jquery-2.1.1.min.js,jquery-1.9.1.min.js,jquery.knob.js");
      bO = a("vr_retry_count_v1", var3);
      bP = a("cr_retry_count_v1", var3);
      bQ = a("incent_warning_enabled", var2);
      bR = a("text_incent_warning_title", "Attention!");
      bS = a("text_incent_warning_body", "You won’t get your reward if the video hasn’t finished.");
      bT = a("text_incent_warning_close_option", "Close");
      bU = a("text_incent_warning_continue_option", "Keep Watching");
      bV = a("incent_nonvideo_warning_enabled", var2);
      bW = a("text_incent_nonvideo_warning_title", "Attention!");
      bX = a("text_incent_nonvideo_warning_body", "You won’t get your reward if the game hasn’t finished.");
      bY = a("text_incent_nonvideo_warning_close_option", "Close");
      bZ = a("text_incent_nonvideo_warning_continue_option", "Keep Playing");
      ca = a("video_callbacks_for_incent_nonvideo_ads_enabled", var4);
      cb = a("check_webview_has_gesture", var2);
      cc = a("close_button_touch_area", var1);
      cd = a("viewability_adview_imp_delay_ms", TimeUnit.SECONDS.toMillis(1L));
      ce = a("viewability_adview_banner_min_width", 320);
      cf = a("viewability_adview_banner_min_height", AppLovinAdSize.BANNER.getHeight());
      cg = a("viewability_adview_mrec_min_width", AppLovinAdSize.MREC.getWidth());
      ch = a("viewability_adview_mrec_min_height", AppLovinAdSize.MREC.getWidth());
      ci = a("viewability_adview_leader_min_width", 728);
      cj = a("viewability_adview_leader_min_height", AppLovinAdSize.LEADER.getWidth());
      ck = a("viewability_adview_min_alpha", 10.0F);
      cl = a("viewability_timer_min_visible_ms", TimeUnit.SECONDS.toMillis(1L));
      cm = a("viewability_timer_interval_ms", 100L);
      cn = a("dismiss_expanded_adview_on_refresh", var2);
      co = a("dismiss_expanded_adview_on_detach", var2);
      cp = a("contract_expanded_ad_on_close", var4);
      cq = a("expandable_close_button_animation_duration_ms", 300L);
      cr = a("expandable_close_button_size", 27);
      cs = a("expandable_h_close_button_margin", var6);
      ct = a("expandable_t_close_button_margin", var6);
      cu = a("expandable_lhs_close_button", var2);
      cv = a("expandable_close_button_touch_area", var1);
      cw = a("click_failed_expand", var2);
      cx = a("auxiliary_operations_threads", 3);
      cy = a("caching_operations_threads", 8);
      cz = a("fullscreen_ad_pending_display_state_timeout_ms", TimeUnit.SECONDS.toMillis(10L));
      cA = a("fullscreen_ad_showing_state_timeout_ms", TimeUnit.MINUTES.toMillis(2L));
      cB = a("lhs_close_button_video", var2);
      cC = a("close_button_right_margin_video", 4);
      cD = a("close_button_size_video", 30);
      cE = a("close_button_top_margin_video", 8);
      cF = a("close_fade_in_time", 400);
      cG = a("show_close_on_exit", var4);
      cH = a("video_countdown_clock_margin", var6);
      cI = a("video_countdown_clock_gravity", 83);
      cJ = a("countdown_clock_size", 32);
      cK = a("countdown_clock_stroke_size", 4);
      cL = a("countdown_clock_text_size", 28);
      cM = a("draw_countdown_clock", var4);
      cN = a("force_back_button_enabled_always", var2);
      cO = a("force_back_button_enabled_close_button", var2);
      cP = a("force_back_button_enabled_poststitial", var2);
      cQ = a("force_hide_status_bar_delay_ms", var5);
      cR = a("handle_window_actions", var2);
      cS = a("inter_display_delay", 200L);
      cT = a("lock_specific_orientation", var2);
      cU = a("lhs_skip_button", var4);
      cV = a("soft_buttons_resource_id", "config_showNavigationBar");
      cW = a("countdown_toggleable", var2);
      cX = a("track_app_killed", var2);
      cY = a("should_use_animated_mute_icon", var2);
      cZ = a("mute_controls_enabled", var2);
      da = a("allow_user_muting", var4);
      db = a("mute_videos", var2);
      dc = a("show_mute_by_default", var2);
      dd = a("mute_with_user_settings", var4);
      de = a("mute_button_size", 32);
      df = a("mute_button_margin", var6);
      dg = a("mute_button_gravity", 85);
      dh = a("video_immersive_mode_enabled", var2);
      di = a("progress_bar_step", 25L);
      dj = a("progress_bar_scale", 10000);
      dk = a("progress_bar_vertical_padding", -8);
      dl = a("video_resume_delay", 250L);
      dm = a("is_video_skippable", var2);
      dn = a("vs_buffer_indicator_size", 50);
      do = a("video_zero_length_as_computed", var2);
      dp = a("set_poststitial_muted_initial_delay_ms", 500L);
      dq = a("widget_fail_on_slot_count_diff", var4);
      dr = a("native_batch_precache_count", var3);
      ds = a("submit_postback_timeout", (int)TimeUnit.SECONDS.toMillis(10L));
      dt = a("submit_postback_retries", 4);
      du = a("max_postback_attempts", 3);
      dv = a("get_retry_delay_v1", (int)TimeUnit.SECONDS.toMillis(10L));
      dw = a("http_connection_timeout", (int)TimeUnit.SECONDS.toMillis(30L));
      dx = a("http_socket_timeout", (int)TimeUnit.SECONDS.toMillis(20L));
      dy = a("force_ssl", var2);
      dz = a("network_available_if_none_detected", var4);
      dA = a("fetch_ad_connection_timeout", (int)TimeUnit.SECONDS.toMillis(30L));
      dB = a("fetch_ad_retry_count_v1", var3);
      dC = a("submit_data_retry_count_v1", var3);
      dD = a("response_buffer_size", 16000);
      dE = a("fetch_basic_settings_connection_timeout_ms", (int)TimeUnit.SECONDS.toMillis(10L));
      dF = a("fetch_basic_settings_retry_count", 3);
      dG = a("fetch_basic_settings_on_reconnect", var2);
      dH = a("skip_fetch_basic_settings_if_not_connected", var2);
      dI = a("fetch_basic_settings_retry_delay_ms", (int)TimeUnit.SECONDS.toMillis(2L));
      dJ = a("fetch_variables_connection_timeout_ms", (int)TimeUnit.SECONDS.toMillis(5L));
      dK = a("preload_persisted_zones", var4);
      dL = a("persist_zones", var2);
      dM = a("ad_session_minutes", 60);
      dN = a("session_tracking_cooldown_on_event_fire", var4);
      dO = a("session_tracking_resumed_cooldown_minutes", 90L);
      dP = a("session_tracking_paused_cooldown_minutes", 90L);
      dQ = a("track_app_paused", var2);
      dR = a("qq", var2);
      dS = a("qq1", var4);
      dT = a("qq3", var4);
      dU = a("qq4", var4);
      dV = a("qq5", var4);
      dW = a("qq6", var4);
      dX = a("qq7", var4);
      dY = a("qq8", var4);
      dZ = a("pui", var4);
      ea = a("plugin_version", "");
      eb = a("hgn", var2);
      ec = a("citab", var2);
      ed = a("cit", var2);
      ee = a("cso", var2);
      ef = a("cfs", var2);
      eg = a("cmi", var2);
      eh = a("cvs", var2);
      ei = a("caf", var2);
      ej = a("cf", var2);
      ek = a("emulator_hardware_list", "ranchu,goldfish,vbox");
      el = a("emulator_device_list", "generic,vbox");
      em = a("emulator_manufacturer_list", "Genymotion");
      en = a("emulator_model_list", "Android SDK built for x86");
      eo = a("adr", var2);
      ep = a("volume_normalization_factor", 6.6666665F);
      eq = a("user_agent_collection_enabled", var2);
      er = a("user_agent_collection_timeout_ms", 600L);
      es = a("webview_package_name", "com.google.android.webview");
      et = a("collect_device_angle", var2);
      eu = a("collect_device_movement", var2);
      ev = a("movement_degradation", 0.75F);
      ew = a("device_sensor_period_ms", 250);
      ex = a("is_track_ad_info", var4);
      ey = a("submit_ad_stats_enabled", var2);
      ez = a("submit_ad_stats_connection_timeout", (int)TimeUnit.SECONDS.toMillis(30L));
      eA = a("submit_ad_stats_retry_count", var3);
      eB = a("submit_ad_stats_max_count", 500);
      eC = a("asdm", var2);
      eD = a("task_stats_enabled", var2);
      eE = a("error_reporting_enabled", var2);
      eF = a("error_reporting_log_limit", 100);
      eG = a("vast_image_html", "<html><head><style>html,body{height:100%;width:100%}body{background-image:url({SOURCE});background-repeat:no-repeat;background-size:contain;background-position:center;}a{position:absolute;top:0;bottom:0;left:0;right:0}</style></head><body><a href=\"applovin://com.applovin.sdk/adservice/track_click_now\"></a></body></html>");
      eH = a("vast_link_html", "<html><head><style>html,body,iframe{height:100%;width:100%;}body{margin:0}iframe{border:0;overflow:hidden;position:absolute}</style></head><body><iframe src={SOURCE} frameborder=0></iframe></body></html>");
      eI = a("vast_max_response_length", 640000);
      eJ = a("vast_max_wrapper_depth", 5);
      eK = a("vast_progress_tracking_countdown_step", TimeUnit.SECONDS.toMillis(1L));
      eL = a("vast_unsupported_video_extensions", "ogv,flv");
      eM = a("vast_unsupported_video_types", "video/ogg,video/x-flv");
      eN = a("vast_validate_with_extension_if_no_video_type", var4);
      eO = a("vast_video_selection_policy", j.a.c.ordinal());
      eP = a("vast_wrapper_resolution_retry_count_v1", var3);
      eQ = a("vast_wrapper_resolution_connection_timeout", (int)TimeUnit.SECONDS.toMillis(30L));
      eR = a("ree", var4);
      eS = a("btee", var4);
      eT = a("server_timestamp_ms", var5);
      eU = a("device_timestamp_ms", var5);
      eV = a("immediate_render", var2);
      eW = a("cleanup_webview", var2);
      eX = a("sanitize_webview", var2);
      eY = a("force_rerender", var2);
      eZ = a("ignore_is_showing", var2);
      fa = a("render_empty_adview", var4);
      fb = a("daostr", var2);
      fc = a("urrr", var2);
      fd = a("tctpmw", var2);
      fe = a("tctlaa", var2);
      ff = a("swvb", var2);
      fg = a("rwvdv", var2);
      fh = a("sfawv", var2);
      fi = a("config_consent_dialog_state", "unknown");
   }

   public d(String var1, Object var2) {
      if (var1 != null) {
         if (var2 != null) {
            this.c = var1;
            this.d = var2;
         } else {
            throw new IllegalArgumentException("No default value specified");
         }
      } else {
         throw new IllegalArgumentException("No name specified");
      }
   }

   protected static d a(String var0, Object var1) {
      if (var1 != null) {
         if (a.contains(var1.getClass())) {
            d var2 = new d(var0, var1);
            if (!b.containsKey(var0)) {
               b.put(var0, var2);
               return var2;
            } else {
               StringBuilder var3 = new StringBuilder();
               var3.append("Setting has already been used: ");
               var3.append(var0);
               throw new IllegalArgumentException(var3.toString());
            }
         } else {
            StringBuilder var7 = new StringBuilder();
            var7.append("Unsupported value type: ");
            var7.append(var1.getClass());
            throw new IllegalArgumentException(var7.toString());
         }
      } else {
         throw new IllegalArgumentException("No default value specified");
      }
   }

   public static Collection c() {
      return Collections.synchronizedCollection(b.values());
   }

   Object a(Object var1) {
      return this.d.getClass().cast(var1);
   }

   public String a() {
      return this.c;
   }

   public Object b() {
      return this.d;
   }

   public int compareTo(Object var1) {
      if (var1 instanceof d) {
         String var2 = ((d)var1).a();
         return this.c.compareTo(var2);
      } else {
         return 0;
      }
   }
}
